swagger: '2.0'
info:
  title: Vtodo Application
  description: Simple backend for todo application.
  version: "1.0.0"
  contact:
      name: Michal
      url: http://yoryor.me
      email: yaoyao0777@gmail.com
  license:
    name:
    url:
# change to your deploy host
host: app.yoryor.me
basePath: /api/v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: groupA
    description: '标签分组1'
  - name: groupB
    description: '标签分组2'
paths:
  /todos:
    get:
      summary:  '获取待办事项列表'
      tags:
        - groupA
      responses:
        200:
          description: Succeeded
          schema:
            type: array
            items:
              $ref: '#/definitions/Todo'
        503:
          description: Service Unavailable
      operationId: listTodos

    post:
      summary:  '创建待办事项'
      tags:
        - groupB
      responses:
        200:
          description: Succeeded
          schema:
              $ref: '#/definitions/Todo'
        400:
          description: Bad Request
        503:
          description: Service Unavailable
      operationId: createTodo


    delete:
      summary:  '删除待办事项列表'
      tags:
        - groupA
      responses:
        204:
          description: Succeeded
        503:
          description: Service Unavailable.
      operationId: deleteTodoList

  /todos/{todoId}:
    get:
      summary: '获取待办事项'
      tags:
        - groupB
      parameters:
        - name: todoId
          in: path
          required: true
          description: 待办事项 ID.
          type: string
      responses:
        200:
          description: Succeeded.
          schema:
            $ref: '#/definitions/Todo'
        404:
          description: Not found.
      operationId: getTodoById

    delete:
      summary: '删除待办事项'
      tags:
        - groupB
      parameters:
        - name: todoId
          in: path
          required: true
          description: 待办事项 ID.
          type: string
      responses:
        204:
          description: Succeeded.
        503:
          description: Service unavailable.
      operationId: deleteTodoById

    patch:
      summary: '更新待办事项'
      tags:
        - groupB
      parameters:
        - name: todoId
          in: path
          required: true
          description: 待办事项 ID.
          type: string
      responses:
        200:
          description: Succeeded.
          schema:
            $ref: '#/definitions/Todo'
        400:
          description: Bad Request.
      operationId: updateTodoById

definitions:
  Todo:
    type: object
    properties:
      id:
        type: string
        description: 待办事项ID.
      title:
        type: string
        description: 待办事项标题.
      completed:
        type: boolean
        description: 待办事项完成状态.
      order:
        type: integer
        description: 待办事项顺序.
      url:
        type: string
        description: 待办事项链接.